version: '2'

services:

  nginx:
   image: nginx:alpine
   ports:
     - '8082:8082'
   volumes:
     - './conf/nginx.conf:/etc/nginx/nginx.conf:ro'
     - './logs/:/var/log/nginx'
   links:
     - 'moodle'
   volumes_from:
     - 'moodle'

  moodle_db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ONETIME_PASSWORD: 'yes'
      MYSQL_DATABASE: '${MOODLE_DB_NAME}'
      MYSQL_USER: '${MOODLE_DB_USER}'
      MYSQL_PASSWORD: '${MOODLE_DB_PASSWORD}'

  moodle:
    image: ellakcy/moodle:mysql_maria_fpm_alpine
    volumes:
      - './data/moodle:/var/moodledata'
      - './data/moodle/www:/var/www/html'
    links:
      - 'moodle_db'
    environment:
      MOODLE_URL: $MOODLE_URL
      MOODLE_ADMIN: $MOODLE_ADMIN
      MOODLE_ADMIN_PASSWORD: $MOODLE_ADMIN_PASSWORD
      MOODLE_ADMIN_EMAIL: $MOODLE_ADMIN_EMAIL
      MOODLE_DB_TYPE: 'mysqli'
      MOODLE_DB_HOST: 'moodle_db'
      MOODLE_DB_USER: $MOODLE_DB_USER
      MOODLE_DB_PASSWORD: $MOODLE_DB_PASSWORD
      MOODLE_DB_NAME: $MOODLE_DB_NAME
      MOODLE_REVERSE_LB: $MOODLE_REVERSE_LB
      MOODLE_SSL: $MOODLE_SSL
      MOODLE_EMAIL_TYPE_QMAIL: MOODLE_EMAIL_TYPE_QMAIL
      MOODLE_EMAIL_HOST: MOODLE_EMAIL_HOST
